from setuptools import setup, find_packages

setup(
    name='QuantumScope',
    version='0.1',
    packages=find_packages(),
    author='Francesco Perrone',
    author_email='francescoperr@gmail.com',
    description='QuantumScope is a comprehensive Python package specifically designed to handle and analyze data in the realm of condensed matter physics, X-Ray Fluorescence (XRF), and various microscopy techniques. Its powerful features are designed to manage and interpret large, multidimensional datasets efficiently and accurately. At the heart of QuantumScope lies an advanced algorithmic core that can dissect intricate patterns in condensed matter physics data, elucidating properties and behaviors that are key to advancing research and development in this field. Similarly, it has robust capabilities for interpreting XRF data, supporting the extraction of elemental composition and distribution information from your samples with precision. Furthermore, QuantumScope excels in analyzing microscopy data, whether from electron microscopy, scanning probe microscopy, or other techniques. Its multidimensional data handling capabilities are particularly potent in dealing with the voluminous data generated by modern microscopy techniques. With QuantumScope, data visualization, interpretation, and manipulation become streamlined processes, empowering researchers to gain insights from their data more quickly and easily. Overall, QuantumScope is not just a tool but a comprehensive solution for researchers delving into the world of condensed matter, aiming to uncover the secrets of materials at the smallest scales. With its emphasis on handling large datasets and providing precise, meaningful output, QuantumScope is the future-ready Python package you need to elevate your research.',
    long_description=open('README.md').read(),
    url='https://github.com/FrancescoPerrone/QuantumScope',
    install_requires=[
        'numpy',
        'h5py',
        'py4DSTEM'
    ],
    classifiers=[
        'Programming Language :: Python :: 3.8',
    ],
)
